# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksharlen <ksharlen@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/28 18:24:03 by ksharlen          #+#    #+#              #
#    Updated: 2020/02/01 16:15:21 by ksharlen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME			:=	gapbuf

SRC_GAPBUF		:=	gap_interface.c\
						gap_del_interface.c\
						gap_cpi_interface.c\
						gap_move_gapbuf.c\
						gap_puthcar_sym_to_buf.c\
						gap_common.c\
						gap_print.c